### ISSUE TITLE
mesapy create two files when once call mesatee_save_file_for_xxx

### ISSUE THREAD

**Issue by luoyanhua2011** [apache/incubator-mesatee#63]
run examples\py_file\py_file.sh, mesapy will create six result files.

The following three functions will create two files with the same content when they are executed：
mesatee.mesatee_save_file_for_task_creator
mesatee.mesatee_save_file_for_all_participants
mesatee.mesatee_save_file_for_file_owner

In this sample, it should create only three files

**Comment by mssun** [comment]
I can confirm this issue.

https://github.com/mesalock-linux/mesapy/blob/sgx/pypy/module/mesatee/interp_mesatee.py#L106

Should be `if ret < 0`. I'll fix ASAP.
